networks:
  ts-mongo-net:
volumes:
  mongo-data:
services:
  ts-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.v1
    ports:
      - "4173:4173"
    depends_on:
      - ts-backend
    networks:
      - ts-mongo-net

  ts-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.v1

    ports:
      - "5000:5000"

    environment:
      - MONGO_URI=mongodb://mongodb-container:27017/notesdb
      - PORT=5000
    
    depends_on:
      - mongodb-container

    networks:
      - ts-mongo-net
    
  mongodb-container:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - ts-mongo-net
