FROM node:22.13.1-slim
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

ENV NODE_ENV=production
EXPOSE 4173

# No borres node_modules, usa npm run preview en lugar de npx
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0"]